server:
  port: 8080
  addr: 127.0.0.1
log:
  # 这里有几个导出方案
  # stdout
  # stderr
  # <path>
  output:
    - "stdout"
    - "/var/log/waveform/latest.log"
  errOutput:
    - "stderr"
    - "/var/log/waveform/error.log"
  # e.g. json console console_with_color
  format: json
  # 规范需要符合 zap 日志库的 zapcore.ParseLevel 的规范
  level: info
device:
  portName: "/dev/ttyUSB0"